In [22]:
import pandas as pd
import numpy as np
import tensorflow as tf
from keras.models import load_model
import ast
pd.set_option("display.max_rows", 500, "display.max_columns", 500)

In [23]:
traits = ["Openness", "Agreeableness", "Persistence", "Cooperativeness", "Openness to Experience", "Adjustment", "Ambition", "Learning Approach"]

f = open("CorrelatedQs.txt", "r")
questions_dict = f.readline()
questions_dict = ast.literal_eval(questions_dict)

# tp = pd.read_excel('temp.xlsx')
tp = pd.read_csv('questions.csv')

In [24]:
trait = "Openness"

model_Openness = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Openness = model_Openness.predict(x)

y_pred_Openness

array([[43.466732],
       [43.621258],
       [81.69764 ],
       ...,
       [79.248375],
       [73.04343 ],
       [76.70884 ]], dtype=float32)

In [25]:
trait = "Cooperativeness"

model_Cooperativeness = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Cooperativeness = model_Cooperativeness.predict(x)

y_pred_Cooperativeness

array([[51.18527 ],
       [43.09831 ],
       [67.04421 ],
       ...,
       [72.57057 ],
       [57.82095 ],
       [65.507454]], dtype=float32)

In [26]:
trait = "Adjustment"

model_Adjustment = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Adjustment = model_Adjustment.predict(x)

y_pred_Adjustment

array([[44.80728 ],
       [66.20973 ],
       [10.561227],
       ...,
       [29.683996],
       [35.882275],
       [43.42988 ]], dtype=float32)

In [27]:
trait = "Persistence"

model_Persistence = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Persistence = model_Persistence.predict(x)

y_pred_Persistence

array([[30.548325],
       [43.232555],
       [59.391586],
       ...,
       [61.682842],
       [49.59503 ],
       [74.05533 ]], dtype=float32)

In [28]:
trait = "Agreeableness"

model_Agreeableness = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Agreeableness = model_Agreeableness.predict(x)

y_pred_Agreeableness

array([[68.1137  ],
       [55.006634],
       [48.11095 ],
       ...,
       [74.83115 ],
       [69.473145],
       [80.0913  ]], dtype=float32)

In [29]:
trait = "Ambition"

model_Ambition = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Ambition = model_Ambition.predict(x)

y_pred_Ambition

array([[20.959023],
       [63.81392 ],
       [39.173687],
       ...,
       [59.432327],
       [17.809113],
       [49.685078]], dtype=float32)

In [30]:
trait = "Openness to Experience"

model_Openness_to_Experience = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Openness_to_Experience = model_Openness_to_Experience.predict(x)

y_pred_Openness_to_Experience

array([[39.827232],
       [44.984016],
       [87.12184 ],
       ...,
       [82.42549 ],
       [61.32259 ],
       [74.948906]], dtype=float32)

In [31]:
trait = "Learning Approach"

model_Learning_Approach = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Learning_Approach = model_Learning_Approach.predict(x)

y_pred_Learning_Approach

array([[ 4.5881014],
       [57.15011  ],
       [59.69416  ],
       ...,
       [81.578186 ],
       [59.740063 ],
       [57.899345 ]], dtype=float32)