In [13]:
import pandas as pd
import numpy as np
import tensorflow as tf
from keras.models import load_model
import ast
pd.set_option("display.max_rows", 500, "display.max_columns", 500)

In [14]:
traits = ["Openness", "Agreeableness", "Persistence", "Cooperativeness", "Openness to Experience", "Adjustment", "Ambition", "Learning Approach"]

f = open("CorrelatedQs.txt", "r")
questions_dict = f.readline()
questions_dict = ast.literal_eval(questions_dict)

# tp = pd.read_excel('temp.xlsx')
# tp = pd.read_csv('questions.csv')

In [15]:
trait = "Openness"

model_Openness = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Openness = model_Openness.predict(x)

y_pred_Openness

array([[44.89287 ],
       [45.74052 ],
       [83.39206 ],
       ...,
       [80.5985  ],
       [75.46759 ],
       [78.954445]], dtype=float32)

In [16]:
trait = "Cooperativeness"

model_Cooperativeness = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Cooperativeness = model_Cooperativeness.predict(x)

y_pred_Cooperativeness

array([[51.041485],
       [42.816784],
       [67.36463 ],
       ...,
       [72.66756 ],
       [57.751503],
       [65.707726]], dtype=float32)

In [17]:
trait = "Adjustment"

model_Adjustment = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Adjustment = model_Adjustment.predict(x)

y_pred_Adjustment

array([[51.927998],
       [73.865036],
       [ 9.673351],
       ...,
       [33.75616 ],
       [38.5367  ],
       [47.359154]], dtype=float32)

In [18]:
trait = "Persistence"

model_Persistence = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Persistence = model_Persistence.predict(x)

y_pred_Persistence

array([[30.730446],
       [43.251717],
       [59.27708 ],
       ...,
       [61.727123],
       [49.61645 ],
       [74.18386 ]], dtype=float32)

In [19]:
trait = "Agreeableness"

model_Agreeableness = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Agreeableness = model_Agreeableness.predict(x)

y_pred_Agreeableness

array([[69.3545 ],
       [53.76764],
       [50.40706],
       ...,
       [75.01481],
       [68.10154],
       [80.94595]], dtype=float32)

In [20]:
trait = "Ambition"

model_Ambition = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Ambition = model_Ambition.predict(x)

y_pred_Ambition

array([[23.950096],
       [65.04518 ],
       [33.58826 ],
       ...,
       [59.561714],
       [16.902847],
       [49.255863]], dtype=float32)

In [21]:
trait = "Openness to Experience"

model_Openness_to_Experience = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Openness_to_Experience = model_Openness_to_Experience.predict(x)

y_pred_Openness_to_Experience

array([[39.372787],
       [44.625725],
       [87.0917  ],
       ...,
       [82.710785],
       [60.554653],
       [74.92161 ]], dtype=float32)

In [22]:
trait = "Learning Approach"

model_Learning_Approach = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Learning_Approach = model_Learning_Approach.predict(x)

y_pred_Learning_Approach

array([[ 7.096819],
       [56.702484],
       [58.828323],
       ...,
       [81.018105],
       [59.334755],
       [57.466675]], dtype=float32)