In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from keras.models import load_model
pd.set_option("display.max_rows", 500, "display.max_columns", 500)

In [2]:
traits = ["Openness", "Agreeableness", "Persistence", "Cooperativeness", "Openness to Experience", "Adjustment", "Ambition", "Learning Approach"]
questions_dict = {'Openness': ['Q7A', 'Q19A', 'Q26A', 'Q27A', 'Q59A', 'Q75A', 'Q76A', 'Q84A', 'Q94A', 'Q100A', 'Q115A', 'Q138A', 'Q139A', 'Q150A', 'Q153A', 'Q161A'], 'Agreeableness': ['Q8A', 'Q9A', 'Q11A', 'Q12A', 'Q16A', 'Q19A', 'Q23A', 'Q24A', 'Q32A', 'Q34A', 'Q40A', 'Q46A', 'Q50A', 'Q51A', 'Q52A', 'Q62A', 'Q65A', 'Q77A', 'Q80A', 'Q86A', 'Q87A', 'Q97A', 'Q104A', 'Q111A', 'Q118A', 'Q119A', 'Q123A', 'Q129A', 'Q130A', 'Q172A', 'Q181A'], 'Persistence': ['Q4A', 'Q5A', 'Q13A', 'Q14A', 'Q22A', 'Q25A', 'Q31A', 'Q48A', 'Q81A', 'Q101A', 'Q110A', 'Q116A', 'Q137A', 'Q141A', 'Q144A', 'Q145A', 'Q152A', 'Q167A'], 'Cooperativeness': ['Q6A', 'Q8A', 'Q9A', 'Q10A', 'Q11A', 'Q12A', 'Q19A', 'Q23A', 'Q24A', 'Q34A', 'Q40A', 'Q50A', 'Q51A', 'Q52A', 'Q62A', 'Q65A', 'Q77A', 'Q80A', 'Q85A', 'Q97A', 'Q111A', 'Q114A', 'Q117A', 'Q123A', 'Q166A', 'Q172A'], 'Openness to Experience': ['Q7A', 'Q26A', 'Q27A', 'Q28A', 'Q43A', 'Q68A', 'Q75A', 'Q83A', 'Q84A', 'Q94A', 'Q100A', 'Q115A', 'Q138A', 'Q139A', 'Q154A', 'Q161A'], 'Adjustment': ['Q1A', 'Q8A', 'Q22A', 'Q24A', 'Q29A', 'Q31A', 'Q33A', 'Q34A', 'Q49A', 'Q57A', 'Q60A', 'Q62A', 'Q71A', 'Q96A', 'Q117A', 'Q123A', 'Q125A', 'Q129A', 'Q134A', 'Q136A', 'Q147A', 'Q148A', 'Q160A', 'Q162A', 'Q173A', 'Q175A', 'Q180A'], 'Ambition': ['Q1A', 'Q4A', 'Q6A', 'Q21A', 'Q22A', 'Q29A', 'Q30A', 'Q31A', 'Q33A', 'Q38A', 'Q49A', 'Q57A', 'Q71A', 'Q72A', 'Q88A', 'Q89A', 'Q96A', 'Q99A', 'Q101A', 'Q116A', 'Q117A', 'Q118A', 'Q123A', 'Q134A', 'Q145A', 'Q147A', 'Q152A', 'Q157A', 'Q160A', 'Q162A', 'Q163A', 'Q164A', 'Q175A'], 'Learning Approach': ['Q55A', 'Q58A', 'Q67A', 'Q68A', 'Q69A', 'Q106A', 'Q107A', 'Q110A']}
# tp = pd.read_excel('temp.csv', index_col=None, header=None)
tp = pd.read_csv('questions.csv')

In [3]:
trait = "Openness"

model_Openness = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Openness = model_Openness.predict(x)

y_pred_Openness

array([[44.89287 ],
       [45.74052 ],
       [83.39206 ],
       ...,
       [80.598495],
       [75.46759 ],
       [78.954445]], dtype=float32)

In [4]:
trait = "Cooperativeness"

model_Cooperativeness = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Cooperativeness = model_Cooperativeness.predict(x)

y_pred_Cooperativeness

array([[51.041485],
       [42.816784],
       [67.36463 ],
       ...,
       [72.667564],
       [57.7515  ],
       [65.707726]], dtype=float32)

In [5]:
trait = "Adjustment"

model_Adjustment = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Adjustment = model_Adjustment.predict(x)

y_pred_Adjustment

array([[51.927998],
       [73.865036],
       [ 9.673351],
       ...,
       [33.756157],
       [38.5367  ],
       [47.359154]], dtype=float32)

In [6]:
trait = "Persistence"

model_Persistence = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Persistence = model_Persistence.predict(x)

y_pred_Persistence

array([[30.730444],
       [43.251717],
       [59.277084],
       ...,
       [61.72712 ],
       [49.616444],
       [74.18386 ]], dtype=float32)

In [7]:
trait = "Agreeableness"

model_Agreeableness = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Agreeableness = model_Agreeableness.predict(x)

y_pred_Agreeableness

array([[69.3545 ],
       [53.76764],
       [50.40706],
       ...,
       [75.0148 ],
       [68.10154],
       [80.94595]], dtype=float32)

In [8]:
trait = "Ambition"

model_Ambition = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Ambition = model_Ambition.predict(x)

y_pred_Ambition

array([[23.950096],
       [65.04518 ],
       [33.58827 ],
       ...,
       [59.561707],
       [16.902851],
       [49.255863]], dtype=float32)

In [9]:
trait = "Openness to Experience"

model_Openness_to_Experience = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Openness_to_Experience = model_Openness_to_Experience.predict(x)

y_pred_Openness_to_Experience

array([[39.372787],
       [44.625725],
       [87.0917  ],
       ...,
       [82.7108  ],
       [60.554653],
       [74.92161 ]], dtype=float32)

In [10]:
trait = "Learning Approach"

model_Learning_Approach = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Learning_Approach = model_Learning_Approach.predict(x)

y_pred_Learning_Approach

array([[ 7.0968184],
       [56.702484 ],
       [58.828323 ],
       ...,
       [81.0181   ],
       [59.334747 ],
       [57.466675 ]], dtype=float32)