In [8]:
import pandas as pd
import numpy as np
import tensorflow as tf
from keras.models import load_model
pd.set_option("display.max_rows", 500, "display.max_columns", 500)

In [9]:
traits = ["Openness", "Agreeableness", "Persistence", "Cooperativeness", "Openness to Experience", "Adjustment", "Ambition", "Learning Approach"]
questions_dict = {'Openness': ['Q7A', 'Q19A', 'Q26A', 'Q27A', 'Q59A', 'Q75A', 'Q76A', 'Q84A', 'Q94A', 'Q100A', 'Q115A', 'Q138A', 'Q139A', 'Q150A', 'Q153A', 'Q161A'], 'Agreeableness': ['Q8A', 'Q9A', 'Q11A', 'Q12A', 'Q16A', 'Q19A', 'Q23A', 'Q24A', 'Q32A', 'Q34A', 'Q40A', 'Q46A', 'Q50A', 'Q51A', 'Q52A', 'Q62A', 'Q65A', 'Q77A', 'Q80A', 'Q86A', 'Q87A', 'Q97A', 'Q104A', 'Q111A', 'Q118A', 'Q119A', 'Q123A', 'Q129A', 'Q130A', 'Q172A', 'Q181A'], 'Persistence': ['Q4A', 'Q5A', 'Q13A', 'Q14A', 'Q22A', 'Q25A', 'Q31A', 'Q48A', 'Q81A', 'Q101A', 'Q110A', 'Q116A', 'Q137A', 'Q141A', 'Q144A', 'Q145A', 'Q152A', 'Q167A'], 'Cooperativeness': ['Q6A', 'Q8A', 'Q9A', 'Q10A', 'Q11A', 'Q12A', 'Q19A', 'Q23A', 'Q24A', 'Q34A', 'Q40A', 'Q50A', 'Q51A', 'Q52A', 'Q62A', 'Q65A', 'Q77A', 'Q80A', 'Q85A', 'Q97A', 'Q111A', 'Q114A', 'Q117A', 'Q123A', 'Q166A', 'Q172A'], 'Openness to Experience': ['Q7A', 'Q26A', 'Q27A', 'Q28A', 'Q43A', 'Q68A', 'Q75A', 'Q83A', 'Q84A', 'Q94A', 'Q100A', 'Q115A', 'Q138A', 'Q139A', 'Q154A', 'Q161A'], 'Adjustment': ['Q1A', 'Q8A', 'Q22A', 'Q24A', 'Q29A', 'Q31A', 'Q33A', 'Q34A', 'Q49A', 'Q57A', 'Q60A', 'Q62A', 'Q71A', 'Q96A', 'Q117A', 'Q123A', 'Q125A', 'Q129A', 'Q134A', 'Q136A', 'Q147A', 'Q148A', 'Q160A', 'Q162A', 'Q173A', 'Q175A', 'Q180A'], 'Ambition': ['Q1A', 'Q4A', 'Q6A', 'Q21A', 'Q22A', 'Q29A', 'Q30A', 'Q31A', 'Q33A', 'Q38A', 'Q49A', 'Q57A', 'Q71A', 'Q72A', 'Q88A', 'Q89A', 'Q96A', 'Q99A', 'Q101A', 'Q116A', 'Q117A', 'Q118A', 'Q123A', 'Q134A', 'Q145A', 'Q147A', 'Q152A', 'Q157A', 'Q160A', 'Q162A', 'Q163A', 'Q164A', 'Q175A'], 'Learning Approach': ['Q55A', 'Q58A', 'Q67A', 'Q68A', 'Q69A', 'Q106A', 'Q107A', 'Q110A']}
tp = pd.read_excel('temp.xlsx')
# tp = pd.read_csv('questions.csv')
tp

Q1A  Q2A  Q3A  Q4A  Q5A  Q6A  Q7A  Q8A  Q9A  Q10A  Q11A  Q12A  Q13A  Q14A  \
0    5    2    1    2    5    2    4    4    2     4     2     4     6     3   

   Q15A  Q16A  Q17A  Q18A  Q19A  Q20A  Q21A  Q22A  Q23A  Q24A  Q25A  Q26A  \
0     1     6     2     1     4     1     7     1     4     5     2     2   

   Q27A  Q28A  Q29A  Q30A  Q31A  Q32A  Q33A  Q34A  Q35A  Q36A  Q37A  Q38A  \
0     5     2     3     7     7     2     2     4     2     1     7     1   

   Q39A  Q40A  Q41A  Q42A  Q43A  Q44A  Q45A  Q46A  Q47A  Q48A  Q49A  Q50A  \
0     3     2     7     6     2     2     6     2     6     4     5     3   

   Q51A  Q52A  Q53A  Q54A  Q55A  Q56A  Q57A  Q58A  Q59A  Q60A  Q61A  Q62A  \
0     3     2     2     2     2     4     5     3     3     4     6     4   

   Q63A  Q64A  Q65A  Q66A  Q67A  Q68A  Q69A  Q70A  Q71A  Q72A  Q73A  Q74A  \
0     6     3     2     2     7     2     2     4     4     5     1     2   

   Q75A  Q76A  Q77A  Q78A  Q79A  Q80A  Q81A  Q82A  Q83A  Q84A  Q85A  Q86A  \
0     2     4     6     2     6     3     5     2     3     6     7     2   

   Q87A  Q88A  Q89A  Q90A  Q91A  Q92A  Q93A  Q94A  Q95A  Q96A  Q97A  Q98A  \
0     4     1     2     2     5     2     6     2     6     7     2     2   

   Q99A  Q100A  Q101A  Q102A  Q103A  Q104A  Q105A  Q106A  Q107A  Q108A  Q109A  \
0     1      4      2      7      6      6      2      2      6      2      7   

   Q110A  Q111A  Q112A  Q113A  Q114A  Q115A  Q116A  Q117A  Q118A  Q119A  \
0      1      3      6      7      2      7      3      4      2      2   

   Q120A  Q121A  Q122A  Q123A  Q124A  Q125A  Q126A  Q127A  Q128A  Q129A  \
0      1      6      6      2      1      3      6      2      2      6   

   Q130A  Q131A  Q132A  Q133A  Q134A  Q135A  Q136A  Q137A  Q138A  Q139A  \
0      2      6      5      2      5      6      2      2      2      2   

   Q140A  Q141A  Q142A  Q143A  Q144A  Q145A  Q146A  Q147A  Q148A  Q149A  \
0      6      5      7      6      3      6      2      3      3      2   

   Q150A  Q151A  Q152A  Q153A  Q154A  Q155A  Q156A  Q157A  Q158A  Q159A  \
0      1      2      6      1      2      6      4      1      4      6   

   Q160A  Q161A  Q162A  Q163A  Q164A  Q165A  Q166A  Q167A  Q168A  Q169A  \
0      6      4      4      2      1      2      3      4      7      2   

   Q170A  Q171A  Q172A  Q173A  Q174A  Q175A  Q176A  Q177A  Q178A  Q179A  \
0      1      7      2      4      2      6      7      6      1      1   

   Q180A  Q181A  
0      3      4

In [10]:
trait = "Openness"

model_Openness = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Openness = model_Openness.predict(x)

y_pred_Openness

array([[44.892868]], dtype=float32)

In [11]:
trait = "Cooperativeness"

model_Cooperativeness = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Cooperativeness = model_Cooperativeness.predict(x)

y_pred_Cooperativeness

array([[51.041485]], dtype=float32)

In [12]:
trait = "Adjustment"

model_Adjustment = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Adjustment = model_Adjustment.predict(x)

y_pred_Adjustment

array([[51.927986]], dtype=float32)

In [13]:
trait = "Persistence"

model_Persistence = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Persistence = model_Persistence.predict(x)

y_pred_Persistence

array([[30.730444]], dtype=float32)

In [14]:
trait = "Agreeableness"

model_Agreeableness = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Agreeableness = model_Agreeableness.predict(x)

y_pred_Agreeableness

array([[69.3545]], dtype=float32)

In [15]:
trait = "Ambition"

model_Ambition = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Ambition = model_Ambition.predict(x)

y_pred_Ambition

array([[23.950094]], dtype=float32)

In [16]:
trait = "Openness to Experience"

model_Openness_to_Experience = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Openness_to_Experience = model_Openness_to_Experience.predict(x)

y_pred_Openness_to_Experience

array([[39.372784]], dtype=float32)

In [17]:
trait = "Learning Approach"

model_Learning_Approach = tf.keras.models.load_model(trait + '.h5')

selected_df = tp[questions_dict[trait]]
x = selected_df.to_numpy()

y_pred_Learning_Approach = model_Learning_Approach.predict(x)

y_pred_Learning_Approach

array([[7.0968194]], dtype=float32)